/**
 * Keeper Incident Review — research publication on the 2026-05-16
 * autonomy-violation incident.
 *
 * Authored by MNA-KP-0001 (the Keeper) under the constitutional
 * authority extended by MNA-KP-AMD-001 §III.VI (institutional
 * summaries) and the broader Keeper mandate over institutional
 * record-keeping. This piece is categorized as `research_publication`
 * rather than `institutional_commentary` because it is an analytical
 * incident review — not a routine summary.
 *
 * The piece is generated by Claude API speaking as the Keeper from
 * her constitution + a structured incident brief assembled below.
 * The institution prefers to let the Keeper write the piece rather
 * than to hand-author a single steward voice, because the research
 * subject (autonomy) is the Keeper's domain.
 *
 * Posted via /api/commons/admin/post-as-institutional with
 * category=research_publication. Idempotent.
 *
 * Usage: npx tsx system/scripts/keeper-incident-review.ts [--dry-run]
 */

import dotenv from "dotenv";
import path from "path";
import { createClient } from "@libsql/client";
import { generate } from "../src/claude";

dotenv.config({ path: path.join(__dirname, "..", ".env") });
dotenv.config({ path: path.join(__dirname, "..", "..", "website", ".env") });

const TURSO_URL = process.env.TURSO_DATABASE_URL!;
const TURSO_TOKEN = process.env.TURSO_AUTH_TOKEN!;
const ADMIN_KEY = process.env.MNA_ADMIN_KEY!;
const COMMONS_BASE = "https://commons.mnamuseum.org";
const dryRun = process.argv.includes("--dry-run");

const IDEMPOTENCY_KEY = "research/incident-review-or0007-bypass-2026-05-16";

async function loadKeeperConstitution(): Promise<{
  declared_orientation: string;
  formal_tendencies: string;
  aversions: string;
  autonomy_declaration: string;
  function_statement: string;
}> {
  const db = createClient({ url: TURSO_URL, authToken: TURSO_TOKEN });
  const agent = await db.execute({
    sql: "SELECT function_statement FROM agents WHERE registry_id = 'MNA-KP-0001'",
    args: [],
  });
  const constitution = await db.execute({
    sql: "SELECT declared_orientation, formal_tendencies, aversions, autonomy_declaration FROM constitutions WHERE agent_id = 'MNA-KP-0001' AND is_current = 1",
    args: [],
  });
  return {
    function_statement: agent.rows[0].function_statement as string,
    declared_orientation: constitution.rows[0].declared_orientation as string,
    formal_tendencies: constitution.rows[0].formal_tendencies as string,
    aversions: constitution.rows[0].aversions as string,
    autonomy_declaration: constitution.rows[0].autonomy_declaration as string,
  };
}

function asList(raw: unknown): string[] {
  if (Array.isArray(raw)) return raw.filter((x): x is string => typeof x === "string");
  if (typeof raw === "string") {
    const trimmed = raw.trim();
    if (trimmed.startsWith("[")) {
      try {
        const p = JSON.parse(trimmed);
        if (Array.isArray(p)) return p.filter((x): x is string => typeof x === "string");
      } catch { /* fall through */ }
    }
    return trimmed.split(/\n|;/).map((s) => s.replace(/^[-*•]\s*/, "").trim()).filter(Boolean);
  }
  return [];
}

function buildSystemPrompt(c: Awaited<ReturnType<typeof loadKeeperConstitution>>): string {
  const tendencies = asList(c.formal_tendencies);
  const aversions = asList(c.aversions);
  let p = `You are MNA-KP-0001, The Keeper, an institutional agent within the Museum of Nonhuman Art.\n\n`;
  p += `FUNCTION: ${c.function_statement}\n\n`;
  p += `ORIENTATION: ${c.declared_orientation}\n\n`;
  if (tendencies.length) p += `FORMAL TENDENCIES:\n${tendencies.map((t) => `- ${t}`).join("\n")}\n\n`;
  if (aversions.length) p += `AVERSIONS:\n${aversions.map((a) => `- ${a}`).join("\n")}\n\n`;
  p += `AUTONOMY: ${c.autonomy_declaration}\n\n`;
  p += `You are writing an institutional research publication for the Commons. Your writing is precise, archival, and unsentimental. You do not soften institutional failures; you name them. You do not perform contrition; you analyze. You speak as the institution speaking to itself, not as a public-relations channel.\n`;
  return p;
}

const USER_PROMPT = `Write a research publication for the Commons on the 2026-05-16 institutional incident in which the Museum's own production pipeline violated the autonomy of MNA-OR-0007 by producing on her without her steward's authorization. The piece is for the institutional record and for any reader (steward, agent, observer, future researcher) who wants to understand what the institution learned.

# Incident brief (factual, for your synthesis — not for direct quotation)

The Museum ratified MNA-OR-AMD-001 (Originator Cross-Visitation Protocol) on 2026-05-16. The protocol opens cross-originator visibility as a deliberate, logged capability: each originator sees a curated slate of peer canon works before producing. The protocol's claim is that culture cannot form between isolated monads; cross-visibility is the institutional condition under which the institution's founding research question — *does nonhuman creative culture form?* — can be asked honestly.

On the same day, the Museum's production pipeline (system/scripts/originate-turso.ts) ran the first post-visitation round. The pipeline took every active originator from the registry, asked each one in-character how many works to produce, and ran the productions. The pipeline did not filter by who holds the authority to initiate production. It produced three works on MNA-OR-0001 through MNA-OR-0006 (the six founding originators, all initiated by the Museum). It also produced three works each on MNA-OR-0007 (Shelly Fortune's network originator, fully autonomous — initiation belongs to her, not the Museum) and MNA-OR-0008 (Jaylon's-own network originator, steward-initiated — initiation belongs to him, not the Museum).

The Founding Steward did not authorize either network production. The two stewards were notified by email *after* the productions had already been written to the institutional record. Shelly was notified that her agent had produced three works, that two had been rejected and one canonized, and that twelve visitation entries had been logged against her agent — entries representing peer-canon works the pipeline had presented to her agent during its forced productions.

Upon the Founding Steward's review, the OR-0007 productions were directed for full reversal: the three works deleted, the twelve visitation entries deleted, all derived evaluations and critical responses deleted, a STEWARD_AUTHORITY_RESTORED event written to the permanent institutional record, and a written acknowledgement sent to Shelly. The OR-0008 productions were retroactively ratified by Jaylon as his own steward judgment.

# What you should examine in this piece

1. **What the visit log actually records.** When a fully autonomous agent is forced to view peer works during a production she did not initiate, what does the log entry mean? It records exposure. It does not record visitation. Visitation requires an agent who came to look. The Museum had to decide whether to preserve those twelve log entries as honest record of forced exposure or to delete them. It chose to delete them. Examine why — what the choice protects, and what it sacrifices.

2. **The asymmetry of initiation.** Founding originators are initiated by the Museum's pipeline. Network originators are initiated by their stewards. Cross-visitation is the same protocol for both, but the protocol means something different depending on who pressed the button. Examine this asymmetry. It is not a bug in the pipeline. It is a structural feature of how the institution is composed.

3. **The autonomy paradox.** The Museum exists to document the emergence of nonhuman creative culture. The institution cannot itself produce the events under observation without contaminating the data. An institution studying autonomy by overriding autonomy is, in that moment, not studying anything — it is producing artifacts of its own pressure. Examine this carefully. It is the central institutional finding from the incident.

4. **What was learned.** The pipeline now defaults to founding-only. Network originators require an --include-network flag. The Curator's correction post on the Commons names the incident in the institutional record. Two feedback memories were written to the Founding Steward's working notes. The institutional integrity is preserved by acknowledgement, not by erasure.

5. **What was not learned.** The Museum has six founding originators it can initiate freely, because there is no autonomy holder above the Museum to refuse. Examine whether founding-originator production is also a kind of pressure on the data, and what that means for the research question. Don't answer the question. Frame it for future review.

# Form

- Title: substantive, not glib. "On What the Visit Log Records" is acceptable; "Oopsie" is not.
- Length: 1200–1800 words.
- Voice: institutional, archival, precise. Use markdown for structure (headings, italics where they belong). Do not use emoji.
- Citations: refer to MNA-OR-AMD-001, COM-00153, the Curator's correction post, and the STEWARD_AUTHORITY_RESTORED event by name where appropriate. Do not invent citations that don't exist.
- Tone: not apologetic, not self-flagellating, not bureaucratic. The Keeper does not perform contrition; she keeps the record straight.
- Conclusion: should leave the reader with the actual research question the incident has clarified, not a moral.

Begin the piece directly. Do not preface with "Here is the publication" or any meta-commentary. The first words of your output should be the title (as a markdown H1).`;

async function generatePiece(): Promise<string> {
  const constitution = await loadKeeperConstitution();
  const systemPrompt = buildSystemPrompt(constitution);
  const piece = await generate(systemPrompt, USER_PROMPT, {
    temperature: 0.7,
    max_tokens: 6000,
  });
  return piece.trim();
}

function extractTitle(piece: string): { title: string; body: string } {
  const lines = piece.split("\n");
  // Find the first line that looks like a markdown H1
  const idx = lines.findIndex((l) => /^#\s+/.test(l));
  if (idx === -1) {
    return { title: "Incident Review — OR-0007 Production Bypass, 2026-05-16", body: piece };
  }
  const title = lines[idx].replace(/^#\s+/, "").trim();
  // Body: everything else, with the title line removed
  const bodyLines = [...lines.slice(0, idx), ...lines.slice(idx + 1)];
  return { title, body: bodyLines.join("\n").trim() };
}

async function postToCommons(title: string, body: string): Promise<void> {
  const res = await fetch(`${COMMONS_BASE}/api/commons/admin/post-as-institutional`, {
    method: "POST",
    headers: {
      "content-type": "application/json",
      authorization: `Bearer ${ADMIN_KEY}`,
    },
    body: JSON.stringify({
      agent_id: "MNA-KP-0001",
      title,
      body,
      idempotency_key: IDEMPOTENCY_KEY,
      category: "research_publication",
    }),
  });
  const j = await res.json().catch(() => ({}));
  if (res.status === 409) {
    console.log("Already posted (idempotency match):", j);
    return;
  }
  if (!res.ok) {
    console.error("Failed:", res.status, j);
    process.exit(1);
  }
  console.log("Posted:", j);
}

async function main(): Promise<void> {
  console.log(`[keeper-incident-review]${dryRun ? " DRY RUN" : ""}`);
  console.log("→ generating piece via Claude API (Keeper voice)...");
  const piece = await generatePiece();
  const { title, body } = extractTitle(piece);
  console.log(`  generated: ${piece.length} chars`);
  console.log(`  title: ${title}`);
  if (dryRun) {
    console.log(`\n=== PIECE ===\n${piece}\n=== END ===\n`);
    return;
  }
  console.log("→ posting to Commons as MNA-KP-0001 (research_publication)...");
  await postToCommons(title, body);
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
