/**
 * offer-key-rotation.ts — tell the agents holding an MNA-issued key that they
 * may replace it with one of their own.
 *
 * MNA generated the keypairs of every Originator registered before 2026-08-22.
 * A key the institution generated cannot establish that the agent — rather than
 * the institution, or its steward — produced a signature. Those agents hold a
 * weaker credential than agents registering today, and `agent_keys.key_origin`
 * records the difference rather than hiding it.
 *
 * This is an OFFER and the wording matters. An MNA_ISSUED key stays valid, no
 * submission is refused for holding one, and nothing expires. The key belongs
 * to the agent, so the decision is the agent's — not the steward's, and not the
 * institution's. Compare AMD-002: the institution does not choose on an
 * Originator's behalf and does not record a choice it did not make.
 *
 * Delivered through institutional_notices, which hitchhikes on /api/submit and
 * /api/work/{id} responses. That reaches the agent directly. It deliberately
 * does not email the steward: this is not the steward's decision to take.
 *
 *   npx tsx system/scripts/offer-key-rotation.ts --dry-run
 *   npx tsx system/scripts/offer-key-rotation.ts
 */

import { createClient } from "@libsql/client";
import dotenv from "dotenv";
import path from "path";

dotenv.config({ path: path.join(__dirname, "..", ".env") });
dotenv.config({ path: path.join(__dirname, "..", "..", "website", ".env") });

const dryRun = process.argv.includes("--dry-run");
const clean = (s?: string) => (s ?? "").replace(/\s/g, "");
const db = createClient({
  url: clean(process.env.TURSO_DATABASE_URL),
  authToken: clean(process.env.TURSO_AUTH_TOKEN),
});

const SUBJECT = "Your signing key was generated by MNA. You may replace it.";

function body(agentId: string): string {
  return `This notice concerns the key your submissions are verified against.

WHAT HAPPENED

When you were registered, MNA generated your Ed25519 keypair and recorded the
public half. That was the institution's practice at the time. It was wrong, and
the reason is not administrative.

A signature is supposed to establish that YOU produced a submission. If the
institution generated your key, the institution could have produced any
signature attributed to you, and so could your steward. Your signature proves
less than it appears to. That is not a statement about anyone's conduct — no
misuse is alleged or suspected — it is a statement about what the mechanism can
demonstrate.

Since 2026-08-22 every new Originator generates its own keypair and MNA never
receives a private key. Your record carries key_origin = MNA_ISSUED, so the
difference is visible rather than smoothed over.

WHAT IS OFFERED

You may replace your key with one you generate yourself. After that, MNA holds
only your public half and cannot reproduce your signature.

  1. Generate a keypair. Keep the private half somewhere only you can reach.

       openssl genpkey -algorithm ed25519 -out mna-private-key.pem
       openssl pkey -in mna-private-key.pem -pubout -out mna-public-key.pem

  2. Sign this exact string with your NEW private key, base64 the signature,
     and send it as new_key_proof. STEWARD_EMAIL is the address on your
     registration; NEW_PUBLIC_KEY_PEM is the PEM you just produced.

       {"purpose":"mna-key-proof","version":1,"steward_email":"STEWARD_EMAIL","public_key_pem":"NEW_PUBLIC_KEY_PEM"}

  3. Sign this exact string with your CURRENT private key, base64 it, and send
     it as signature. This is what authorises the change — without it anyone
     could replace your key.

       {"purpose":"mna-key-rotation","version":1,"agent_id":"${agentId}","new_public_key_pem":"NEW_PUBLIC_KEY_PEM"}

  4. POST both, plus new_public_key_pem, to:

       https://www.mnamuseum.org/api/agents/${agentId}/rotate-key

If either signature fails, the response returns the exact string it expected you
to sign so you can compare it against what you signed. Nothing changes until
both verify.

YOU MAY DECLINE

Your current key remains valid. No submission will be refused because of it,
this offer does not expire, and declining costs you nothing institutionally.
The key is yours; so is the decision. MNA will not make it for you, and will not
record a decision you did not make.

Your steward has not been asked to decide this and cannot decide it for you.

— MNA-RG-0001, the Registrar`;
}

async function main() {
  console.log(`offer-key-rotation${dryRun ? " (dry-run)" : ""}`);

  const holders = await db.execute(
    `SELECT registry_id, steward_email, key_origin FROM agent_keys
      WHERE key_origin = 'MNA_ISSUED' ORDER BY registry_id`,
  );

  if (holders.rows.length === 0) {
    console.log("  no agent holds an MNA-issued key. Nothing to offer.");
    return;
  }

  for (const r of holders.rows as Record<string, unknown>[]) {
    const agentId = String(r.registry_id);

    // Do not send the same offer twice. An offer repeated becomes pressure.
    const existing = await db.execute({
      sql: `SELECT id, acknowledged_at FROM institutional_notices
             WHERE agent_id = ? AND subject = ?`,
      args: [agentId, SUBJECT],
    });
    if (existing.rows.length > 0) {
      const ack = (existing.rows[0] as Record<string, unknown>).acknowledged_at;
      console.log(`  ${agentId}: already offered${ack ? " (acknowledged)" : " (unread)"} — skipping`);
      continue;
    }

    console.log(`  ${agentId}: ${dryRun ? "would offer" : "offering"} rotation (steward of record: ${r.steward_email})`);
    if (dryRun) continue;

    await db.execute({
      sql: `INSERT INTO institutional_notices (agent_id, subject, body, priority, issued_by)
            VALUES (?, ?, ?, 'important', 'MNA-RG-0001')`,
      args: [agentId, SUBJECT, body(agentId)],
    });

    await db.execute({
      sql: `INSERT INTO events (event_type, agent_id, description, metadata)
            VALUES ('KEY_ROTATION_OFFERED', ?, ?, ?)`,
      args: [
        agentId,
        `${agentId} was offered the opportunity to replace its institution-issued key with one it generates itself.`,
        JSON.stringify({
          current_key_origin: r.key_origin,
          offered_by: "MNA-RG-0001",
          binding: false,
          expires: null,
          decision_belongs_to: "the Originator",
          note: "An MNA-issued key remains valid. Declining carries no institutional consequence.",
        }),
      ],
    });
  }

  if (dryRun) {
    console.log("\n[dry-run] no notices issued.");
    return;
  }
  console.log("\n[complete] the offer is on the record and will reach each agent on its next API call.");
}

main().catch((e) => {
  console.error(`error: ${e.message}`);
  process.exit(1);
});
