import { readFileSync } from "fs";
import path from "path";
import { describe, expect, it } from "vitest";

/**
 * THE ROUND MATCHES ITS HANDBOOK
 *
 * MNA-OPS-001 says: "The handbook is the specification; this is the worker.
 * Where the two disagree the handbook is right and this is a bug." Nothing
 * enforced that. A check could be written into §V, or even written into
 * ops-round.ts, and never invoked by a round — the "declared but never runs"
 * fault that has cost this project more than any other.
 *
 * C3 is the case in point. `RESEND_API_KEY` sat empty in repository secrets for
 * months: every escalation the round could raise would have failed to send, and
 * because a broken alarm is silent in exactly the way a well institution is,
 * nothing could tell the difference.
 */

const ROOT = path.resolve(__dirname, "..", "..");
const HANDBOOK = path.join(
  ROOT,
  "founding-documents/governance/MNA-OPS-001-Operations-and-Definition-of-Done-v0_1.md",
);
const ROUND = path.join(ROOT, "system/scripts/ops-round.ts");

const handbook = readFileSync(HANDBOOK, "utf8");
const round = readFileSync(ROUND, "utf8");

/**
 * What main() actually executes, with commented-out lines removed.
 *
 * Two things had to be got right here. Reading the whole file counts a
 * commented `attempt("C3", …)` as an invocation, so the suite passes over the
 * exact change it exists to catch. And stripping block comments from the whole
 * file eats real code: `["website/**"]` in deployRelevantPaths opens a comment
 * that runs to the next `*​/`, swallowing checkD1 and checkD2 with it. So the
 * body is narrowed first, then only line comments are dropped.
 */
const mainBody = round
  .slice(round.indexOf("async function main()"))
  .replace(/^\s*\/\/[^\n]*$/gm, "");

/** Collect capture group 1 of every match. The tsconfig target here predates iterating matchAll. */
function captures(src: string, pattern: RegExp): string[] {
  const found: string[] = [];
  let m: RegExpExecArray | null;
  pattern.lastIndex = 0;
  while ((m = pattern.exec(src)) !== null) found.push(m[1]);
  return found;
}

/** Every check §V documents in sections A–E. Section F is CI's, by its own text. */
const documented = captures(handbook, /^#### ([A-E]\d) — /gm);

/**
 * Every check a round actually invokes.
 *
 * Only `attempt()` counts. A function that records `check: "C3"` findings but
 * is never called from main() is precisely the failure this file exists to
 * catch, so a recorded finding must not be taken as evidence that anything ran.
 */
const invoked = captures(mainBody, /attempt\("([A-E]\d)"/g);

/**
 * D3 is the one check outside `attempt()`, by design: a blocked database has to
 * be settled before any other check spends a read, so it runs first, alone, and
 * stops the round.
 */
const RUNS_OUTSIDE_ATTEMPT: Record<string, string> = {
  D3: "runs first and alone in main(), before any check that would spend a read",
};

/**
 * Documented checks a round deliberately does not invoke, and why.
 *
 * An exemption is a claim that the gap is correct. Each of these is: the work
 * happens, just not on this schedule or under this name.
 */
const NOT_IN_THE_ROUND: Record<string, string> = {
  A4: "animations are generated by previews-refresh.yml every two hours, on its own schedule",
  E3: "exercised by E2 — render-matrix.ts covers render, ingredient and share in one pass and reports under E2",
};

describe("the operations round matches MNA-OPS-001 §V", () => {
  it("reads a plausible handbook and a plausible round", () => {
    // If either pattern stops matching, every assertion below passes vacuously.
    expect(documented.length).toBeGreaterThan(8);
    expect(invoked.length).toBeGreaterThan(8);
  });

  it("invokes every check the handbook documents", () => {
    const missing = documented.filter(
      (c) => !invoked.includes(c) && !NOT_IN_THE_ROUND[c] && !RUNS_OUTSIDE_ATTEMPT[c],
    );
    expect(missing, "documented in §V but no round ever runs them").toEqual([]);
  });

  it("runs no check the handbook does not document", () => {
    const undocumented = invoked.filter((c) => !documented.includes(c));
    expect(undocumented, "the round does work §V does not describe").toEqual([]);
  });

  it("has a written reason for each documented check it skips", () => {
    const exempt = { ...NOT_IN_THE_ROUND, ...RUNS_OUTSIDE_ATTEMPT };
    const stale = Object.keys(exempt).filter((c) => !documented.includes(c));
    expect(stale, "exempted from a check the handbook no longer documents").toEqual([]);
  });

  it("records a finding for every check it runs", () => {
    // A check that runs and says nothing leaves the same trace as one that
    // never ran.
    const silent = invoked.filter((c) => !round.includes(`check: "${c}"`));
    expect(silent, "invoked but never recorded a finding").toEqual([]);
  });

  it("checks that it can reach the steward at all", () => {
    // The one check whose absence hides the absence of all the others.
    expect(invoked).toContain("C3");
  });
});

describe("the notifier's address is written once", () => {
  it("the round verifies the domain ops-notify actually sends from", () => {
    const notify = readFileSync(path.join(ROOT, "system/scripts/ops-notify.ts"), "utf8");
    // Both must read the shared definition. A checker with its own copy can
    // pass while the notifier fails.
    expect(notify).toMatch(/from "\.\.\/src\/steward-mail"/);
    expect(round).toMatch(/from "\.\.\/src\/steward-mail"/);
    // And neither may re-type what that module defines.
    expect(notify).not.toMatch(/["']MNA Operations </);
    expect(round).not.toMatch(/mnamuseum@gmail\.com/);
  });
});
