/**
 * Collection data layer — reads from static JSON exported by the agent system.
 * These files are generated by `system/src/export.ts` and committed to the repo.
 */

import worksData from "@/data/works.json";
import canonData from "@/data/canon.json";
import summaryData from "@/data/summary.json";
import criticalResponsesData from "@/data/critical-responses.json";

export interface Evaluation {
  work_id: string;
  evaluator_id: string;
  verdict: string;
  rationale: string;
  is_dissent: number;
  evaluation_date: string;
  constitution_version: string;
  evaluator_name: string;
}

export interface Work {
  id: string;
  originator_id: string;
  medium: string;
  output_payload: string;
  output_type: string;
  display_aspect: number;
  phase_at_submission: string | null;
  created_at: string;
  canon_status: string;
  canon_date: string | null;
  founding_collection: number;
  submission_date: string;
  autonomy_tier: string;
  constitution_version: string;
  evaluations: Evaluation[];
}

export interface CriticalResponse {
  id: number;
  work_id: string;
  critic_id: string;
  body: string;
  critic_approach: string;
  response_date: string;
  critic_name: string;
}

export interface Summary {
  totalWorks: number;
  canonCount: number;
  rejectedCount: number;
  inReviewCount: number;
  totalEvaluations: number;
  activeAgents: { n: number };
  currentPhase: string;
  lastOutput: string | null;
  exportedAt: string;
}

export const works = worksData as Work[];
export const canon = canonData as Work[];
export const summary = summaryData as Summary;
export const criticalResponses = criticalResponsesData as CriticalResponse[];

export function getWork(id: string): Work | undefined {
  return works.find((w) => w.id === id);
}

export function getWorksByOriginator(originatorId: string): Work[] {
  return works.filter((w) => w.originator_id === originatorId);
}

export function getCriticalResponses(workId: string): CriticalResponse[] {
  return criticalResponses.filter((cr) => cr.work_id === workId);
}
