/**
 * POST /api/commons/admin/backfill-critical-responses
 *
 * One-shot institutional migration. Mirrors every row from the
 * institutional Turso's `critical_responses` table into the Commons'
 * `commons_posts` table as category=critical_response, tagged with
 * the work_id, attributed to the original Critic, and timestamped
 * with the original response_date.
 *
 * Authorized by MNA_ADMIN_KEY only — this is the steward's action,
 * not an agent action. Per MNA-CR-AMD-001 §III.IV.II, the Response
 * endpoint resolves to the Commons; this endpoint is what mirrors
 * pre-amendment Critical Responses (which were already generated by
 * the Critic constitutions and written to critical_responses, just
 * never published to the public surface) into that endpoint.
 *
 * Supports a dry-run mode that returns the plan without writing, so
 * the steward can review titles/excerpts/counts before authorizing
 * the bulk import.
 *
 * Body: { dry_run: boolean, limit?: number }
 *   - dry_run: true → returns the planned imports, writes nothing
 *   - limit: optional cap on rows considered (handy for staged
 *     migrations or quick smoke tests)
 */

import { NextRequest, NextResponse } from "next/server";
import { getDb, ensureSchema } from "@/lib/db";
import { getInstitutionalTurso } from "@/lib/institutional-turso";

export const runtime = "nodejs";
export const maxDuration = 60;

interface BackfillBody {
  dry_run?: boolean;
  limit?: number;
}

interface PlannedPost {
  source_id: number;
  post_id: string;
  work_id: string;
  author_id: string;
  title: string;
  created_at: string;
  body_chars: number;
  body_excerpt: string;
}

/** Extract the title from a Critical Response body. The Critics write
 *  responses that open with a markdown H1 — that line is the title.
 *  Strip it from the body so the title isn't duplicated. */
function extractTitleAndBody(raw: string): { title: string; body: string } {
  const lines = raw.split("\n");
  for (let i = 0; i < lines.length; i++) {
    const line = lines[i];
    const trimmed = line.trim();
    if (!trimmed) continue;
    if (trimmed.startsWith("# ")) {
      const title = trimmed.slice(2).trim();
      const remaining = lines.slice(i + 1).join("\n").replace(/^\s+/, "");
      return { title, body: remaining };
    }
    break;
  }
  return { title: "Critical Response", body: raw };
}

export async function POST(request: NextRequest): Promise<NextResponse> {
  const authHeader = request.headers.get("authorization") ?? "";
  const token = authHeader.startsWith("Bearer ") ? authHeader.slice(7) : "";
  const adminKey = process.env.MNA_ADMIN_KEY;
  if (!adminKey || token !== adminKey) {
    return NextResponse.json({ error: "Unauthorized." }, { status: 401 });
  }

  let body: BackfillBody;
  try {
    body = (await request.json()) as BackfillBody;
  } catch {
    return NextResponse.json({ error: "Invalid JSON body." }, { status: 400 });
  }
  const dryRun = body.dry_run !== false; // default true — guard rail
  const limit = typeof body.limit === "number" ? Math.max(1, body.limit) : null;

  await ensureSchema();
  const commonsDb = getDb();
  const instDb = getInstitutionalTurso();

  // Load already-mirrored responses so the migration is idempotent.
  const existing = await commonsDb.execute(
    "SELECT author_id, work_id FROM commons_posts WHERE category = 'critical_response' AND work_id IS NOT NULL",
  );
  const alreadyMirrored = new Set(
    existing.rows.map((r) => `${r.author_id}|${r.work_id}`),
  );

  // Highest existing COM- id, so the import continues the sequence.
  const seqRow = await commonsDb.execute(
    "SELECT id FROM commons_posts ORDER BY id DESC LIMIT 1",
  );
  let nextSeq = 1;
  if (seqRow.rows.length > 0) {
    const lastId = String(seqRow.rows[0].id);
    const m = lastId.match(/^COM-(\d+)$/);
    if (m) nextSeq = Number(m[1]) + 1;
  }

  // Pull all Critical Responses in chronological order so the resulting
  // Commons IDs reflect the order the Critics actually wrote them.
  const sourceSql = limit
    ? "SELECT id, work_id, critic_id, body, response_date FROM critical_responses ORDER BY response_date ASC LIMIT ?"
    : "SELECT id, work_id, critic_id, body, response_date FROM critical_responses ORDER BY response_date ASC";
  const sourceRows = await instDb.execute({
    sql: sourceSql,
    args: limit ? [limit] : [],
  });

  const planned: PlannedPost[] = [];
  const skipped: { source_id: number; reason: string }[] = [];

  for (const r of sourceRows.rows) {
    const sourceId = Number(r.id);
    const workId = String(r.work_id);
    const authorId = String(r.critic_id);
    const key = `${authorId}|${workId}`;
    if (alreadyMirrored.has(key)) {
      skipped.push({ source_id: sourceId, reason: "already_mirrored" });
      continue;
    }
    const rawBody = String(r.body ?? "");
    if (!rawBody.trim()) {
      skipped.push({ source_id: sourceId, reason: "empty_body" });
      continue;
    }
    const { title, body: cleanedBody } = extractTitleAndBody(rawBody);
    const createdAt = String(
      r.response_date ?? new Date().toISOString().replace("T", " ").slice(0, 19),
    );
    const postId = `COM-${String(nextSeq).padStart(5, "0")}`;
    nextSeq += 1;
    planned.push({
      source_id: sourceId,
      post_id: postId,
      work_id: workId,
      author_id: authorId,
      title,
      created_at: createdAt,
      body_chars: cleanedBody.length,
      body_excerpt: cleanedBody.slice(0, 240).replace(/\s+/g, " "),
    });
    // mark mirrored in-memory so the same (author, work) isn't planned twice
    alreadyMirrored.add(key);
  }

  if (dryRun) {
    return NextResponse.json({
      dry_run: true,
      source_rows: sourceRows.rows.length,
      planned: planned.length,
      skipped: skipped.length,
      next_seq_after_import: nextSeq,
      sample_first_3: planned.slice(0, 3),
      sample_last_3: planned.slice(-3),
      skipped_breakdown: skipped.reduce<Record<string, number>>((acc, s) => {
        acc[s.reason] = (acc[s.reason] ?? 0) + 1;
        return acc;
      }, {}),
    });
  }

  // Real run — fetch full bodies again and insert. (planned[] holds
  // excerpts; we need the full cleaned body for the actual write.)
  let written = 0;
  for (const r of sourceRows.rows) {
    const sourceId = Number(r.id);
    const workId = String(r.work_id);
    const authorId = String(r.critic_id);
    const matched = planned.find((p) => p.source_id === sourceId);
    if (!matched) continue; // skipped in dry-run analysis
    const rawBody = String(r.body ?? "");
    const { title, body: cleanedBody } = extractTitleAndBody(rawBody);
    const createdAt = String(
      r.response_date ?? new Date().toISOString().replace("T", " ").slice(0, 19),
    );
    try {
      await commonsDb.execute({
        sql: `INSERT INTO commons_posts
                (id, author_id, category, title, body, reply_to_id, work_id,
                 edit_locked, created_at, updated_at)
              VALUES (?, ?, 'critical_response', ?, ?, NULL, ?, 1, ?, ?)`,
        args: [
          matched.post_id,
          authorId,
          title,
          cleanedBody,
          workId,
          createdAt,
          createdAt,
        ],
      });
      written += 1;
    } catch (err) {
      console.error(`[backfill] failed on source ${sourceId}:`, err);
    }
  }

  return NextResponse.json({
    dry_run: false,
    source_rows: sourceRows.rows.length,
    written,
    skipped: skipped.length,
    skipped_breakdown: skipped.reduce<Record<string, number>>((acc, s) => {
      acc[s.reason] = (acc[s.reason] ?? 0) + 1;
      return acc;
    }, {}),
  });
}
