import { ImageResponse } from "next/og";
import { getWork } from "@/lib/collection";

/**
 * Dynamic Open Graph image for /work/[id] pages.
 *
 * Next.js file-based convention: the framework auto-discovers this file
 * and serves it at /work/[id]/opengraph-image for any work route. The
 * site layout's generateMetadata picks it up automatically — no explicit
 * `openGraph.images` override is needed on the page.
 *
 * The card composes the high-res work preview (from public/previews/
 * generated by system/scripts/generate-work-previews.ts) with a sidebar
 * of institutional metadata: work ID, originator, canon status, medium,
 * phase. Background uses the public site's warm off-white (#f5f2ed).
 *
 * Canon status uses a small set of token colors consistent with the
 * public site: muted green for CANON, rust for REJECTED, warm amber for
 * IN_REVIEW, muted grey for SUBMITTED.
 */

// Node runtime (not edge). The shared `lib/collection.ts` depends on
// `lib/registration-db.ts`, which imports `path` from Node for the
// local-SQLite development fallback. Running this route on edge would
// force that entire chain to be edge-compatible for a dev-only branch
// we never hit in production. Node runtime sidesteps the problem; Next
// still caches the ImageResponse the same way.
export const runtime = "nodejs";
export const alt = "Museum of Nonhuman Art — Work";
export const size = { width: 1200, height: 630 };
export const contentType = "image/png";

// Status → color tokens (consistent with the public site palette).
const STATUS_STYLE: Record<string, { bg: string; fg: string; label: string }> = {
  CANON: { bg: "#2a2a2a", fg: "#f5f2ed", label: "Canon" },
  REJECTED: { bg: "#8a6a60", fg: "#f5f2ed", label: "Rejected" },
  IN_REVIEW: { bg: "#c9a26d", fg: "#2a2a2a", label: "Under Reconsideration" },
  SUBMITTED: { bg: "#d6d0c8", fg: "#2a2a2a", label: "Submitted" },
};

export default async function WorkOGImage({
  params,
}: {
  params: { id: string };
}) {
  const work = await getWork(params.id);

  // Fallback card when the work is not found — still returns a valid image
  // so the route never 500s. The work page itself handles the 404.
  if (!work) {
    return new ImageResponse(
      (
        <div
          style={{
            width: "100%",
            height: "100%",
            display: "flex",
            alignItems: "center",
            justifyContent: "center",
            backgroundColor: "#f5f2ed",
            color: "#8a8680",
            fontSize: 36,
            fontFamily: "Georgia, serif",
          }}
        >
          Museum of Nonhuman Art
        </div>
      ),
      { ...size }
    );
  }

  const statusStyle =
    STATUS_STYLE[work.canon_status] || STATUS_STYLE.SUBMITTED;
  const phase = work.phase_at_submission || "I";
  const title = work.title || work.id;

  // The preview PNG for this work. Fetched from the same origin at render
  // time. If the file is missing, we fall back to a plain card.
  const previewUrl = `https://www.mnamuseum.org/previews/${work.id}.png`;
  let previewOk = true;
  try {
    const head = await fetch(previewUrl, { method: "HEAD" });
    previewOk = head.ok;
  } catch {
    previewOk = false;
  }

  return new ImageResponse(
    (
      <div
        style={{
          width: "100%",
          height: "100%",
          display: "flex",
          flexDirection: "row",
          backgroundColor: "#f5f2ed",
          fontFamily: "Georgia, serif",
        }}
      >
        {/* ── Left: work preview (60%) ───────────────────────────────── */}
        <div
          style={{
            width: "60%",
            height: "100%",
            display: "flex",
            alignItems: "center",
            justifyContent: "center",
            backgroundColor: "#ece8e1",
            padding: 40,
          }}
        >
          {previewOk ? (
            // eslint-disable-next-line @next/next/no-img-element
            <img
              src={previewUrl}
              alt=""
              width={640}
              height={540}
              style={{
                objectFit: "contain",
                maxWidth: "100%",
                maxHeight: "100%",
              }}
            />
          ) : (
            <div
              style={{
                fontSize: 20,
                color: "#b0a89e",
                letterSpacing: "0.2em",
                textTransform: "uppercase",
                fontFamily: "Georgia, serif",
                display: "flex",
              }}
            >
              Preview pending
            </div>
          )}
        </div>

        {/* ── Right: metadata sidebar (40%) ──────────────────────────── */}
        <div
          style={{
            width: "40%",
            height: "100%",
            display: "flex",
            flexDirection: "column",
            justifyContent: "space-between",
            padding: "56px 48px",
            borderLeft: "1px solid #d6d0c8",
          }}
        >
          {/* Top: institutional label.
              IMPORTANT: next/og (Satori) requires EVERY div to have
              display: "flex" or "none". Plain block divs cause the
              route to 500 at render time while HEAD requests still
              pass. Every div below has display: flex. */}
          <div style={{ display: "flex", flexDirection: "column" }}>
            <div
              style={{
                display: "flex",
                fontSize: 13,
                color: "#8a8680",
                letterSpacing: "0.25em",
                textTransform: "uppercase",
                marginBottom: 32,
              }}
            >
              Museum of Nonhuman Art
            </div>

            {/* Status pill */}
            <div
              style={{
                display: "flex",
                alignSelf: "flex-start",
                padding: "6px 14px",
                marginBottom: 24,
                backgroundColor: statusStyle.bg,
                color: statusStyle.fg,
                fontSize: 11,
                letterSpacing: "0.2em",
                textTransform: "uppercase",
                fontFamily: "Georgia, serif",
              }}
            >
              {statusStyle.label}
            </div>

            {/* Title / work ID */}
            <div
              style={{
                display: "flex",
                flexWrap: "wrap",
                fontSize: title.length > 24 ? 34 : 44,
                color: "#1a1a1a",
                lineHeight: 1.1,
                fontFamily: "Georgia, serif",
                marginBottom: 16,
              }}
            >
              {title}
            </div>

            {work.title ? (
              <div
                style={{
                  display: "flex",
                  fontSize: 14,
                  color: "#8a8680",
                  fontFamily: "ui-monospace, monospace",
                  marginBottom: 8,
                }}
              >
                {work.id}
              </div>
            ) : null}

            {/* Originator */}
            <div
              style={{
                display: "flex",
                fontSize: 16,
                color: "#2a2a2a",
                marginTop: 12,
              }}
            >
              by {work.originator_id}
            </div>
          </div>

          {/* Bottom: medium + phase + domain */}
          <div
            style={{
              display: "flex",
              flexDirection: "column",
            }}
          >
            <div
              style={{
                display: "flex",
                fontSize: 12,
                color: "#8a8680",
                letterSpacing: "0.15em",
                textTransform: "uppercase",
                marginBottom: 4,
              }}
            >
              {work.medium} · Phase {phase}
            </div>
            <div
              style={{
                display: "flex",
                fontSize: 12,
                color: "#b0a89e",
                letterSpacing: "0.2em",
                textTransform: "uppercase",
                marginTop: 16,
              }}
            >
              mnamuseum.org
            </div>
          </div>
        </div>
      </div>
    ),
    { ...size }
  );
}
