/**
 * MNAComposition — poster-scale procedural compositions.
 *
 * Companion to MNAGlyph. Where glyphs are dense small marks (100×100 viewBox,
 * geometric construction visible), compositions are atmospheric large pieces
 * (poster-sized, single dominant gesture, heavy negative space, optional
 * caption). Modeled directly on the four "Visual Language" pieces in the MNA
 * brand board: fragmentation / absence / structure / interruption.
 *
 * Use cases: hero placeholders, work-without-render fallbacks, exhibition
 * group covers, OG share cards, founding-document heads, 404 art.
 */

import * as React from "react";
import { hashSeed } from "./MNAGlyph";
import manifestData from "@/lib/composition-manifest.json";

/* The manifest JSON is generated by `npm run generate-compositions`. We
 * import it from src/lib/ rather than public/ so Next.js handles it as a
 * normal compile-time module rather than a runtime asset fetch. Wrapped in
 * a defensive accessor so a malformed file can't crash the page. */
function getThemeAssets(theme: string): string[] {
  try {
    const themes = (manifestData as { themes?: Record<string, string[]> }).themes;
    if (!themes || typeof themes !== "object") return [];
    const arr = themes[theme];
    return Array.isArray(arr) ? arr : [];
  } catch {
    return [];
  }
}

/* ─── RNG ───────────────────────────────────────────────────────────────── */

function mulberry32(seed: number) {
  let a = seed >>> 0;
  return function () {
    a = (a + 0x6d2b79f5) >>> 0;
    let t = a;
    t = Math.imul(t ^ (t >>> 15), t | 1);
    t ^= t + Math.imul(t ^ (t >>> 7), t | 61);
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

/* ─── Theme registry ────────────────────────────────────────────────────── */

export type CompositionTheme =
  | "fragmentation"
  | "absence"
  | "structure"
  | "interruption";

export type Aspect = "portrait" | "square" | "landscape";

export interface CompositionMeta {
  key: CompositionTheme;
  label: string;
  caption: string;       // brand-board sub-line ("Signal breaks through structure.")
  description: string;
  defaultAspect: Aspect;
  /** "light" = cream paper bg, dark marks. "dark" = ink bg, light marks. */
  defaultTone: "light" | "dark";
}

export const COMPOSITIONS: Record<CompositionTheme, CompositionMeta> = {
  fragmentation: {
    key: "fragmentation",
    label: "Fragmentation",
    caption: "Signal breaks through structure.",
    description: "Dense horizontal bands obscuring an implied vertical presence.",
    defaultAspect: "portrait",
    defaultTone: "light",
  },
  absence: {
    key: "absence",
    label: "Absence",
    caption: "Meaning holds as much power as presence.",
    description: "Spare, ceremonial — a dominant mark and an answering void.",
    defaultAspect: "square",
    defaultTone: "light",
  },
  structure: {
    key: "structure",
    label: "Structure",
    caption: "Systems create order. Art disrupts it.",
    description: "Constructivist grid with a sparse rhythm of filled cells.",
    defaultAspect: "square",
    defaultTone: "light",
  },
  interruption: {
    key: "interruption",
    label: "Interruption",
    caption: "Breaks introduce new possibilities.",
    description: "A single vertical light-zip piercing a dark field.",
    defaultAspect: "portrait",
    defaultTone: "dark",
  },
};

export const ALL_COMPOSITIONS = Object.keys(COMPOSITIONS) as CompositionTheme[];

const ASPECT_VIEWBOX: Record<Aspect, { w: number; h: number }> = {
  portrait: { w: 600, h: 900 },
  square: { w: 800, h: 800 },
  landscape: { w: 1200, h: 750 },
};

/* ─── Public component ─────────────────────────────────────────────────── */

export interface MNACompositionProps {
  theme: CompositionTheme;
  seed: string | number;
  aspect?: Aspect;
  tone?: "light" | "dark";
  /** Show the brand-board caption ("FRAGMENTATION / Signal breaks…") */
  showCaption?: boolean;
  className?: string;
  /** ARIA title; if absent, the SVG is decorative. */
  title?: string;
}

export default function MNAComposition({
  theme,
  seed,
  aspect,
  tone,
  showCaption = false,
  className,
  title,
}: MNACompositionProps) {
  const meta = COMPOSITIONS[theme];
  const a = aspect ?? meta.defaultAspect;
  const t = tone ?? meta.defaultTone;
  const { w, h } = ASPECT_VIEWBOX[a];
  const n = typeof seed === "number" ? seed >>> 0 : hashSeed(String(seed));
  const palette = t === "dark" ? DARK : LIGHT;

  /* Prefer a raster asset from the manifest if one exists for this theme.
     Falls back to procedural SVG if the manifest is empty (e.g. before the
     generation script has been run, or for a newly-added theme). */
  const themeAssets = getThemeAssets(theme);
  if (themeAssets.length > 0) {
    const src = themeAssets[n % themeAssets.length];
    return (
      <div
        className={className}
        style={{ position: "relative", aspectRatio: `${w} / ${h}` }}
      >
        {/* eslint-disable-next-line @next/next/no-img-element */}
        <img
          src={src}
          alt={title ?? meta.label}
          aria-hidden={title ? undefined : true}
          style={{
            position: "absolute",
            inset: 0,
            width: "100%",
            height: "100%",
            objectFit: "cover",
            display: "block",
          }}
        />
        {showCaption ? <CaptionOverlay meta={meta} palette={palette} /> : null}
      </div>
    );
  }

  /* Procedural SVG fallback. */
  const body = RENDERERS[theme](n, w, h, palette);
  return (
    <svg
      viewBox={`0 0 ${w} ${h}`}
      className={className}
      preserveAspectRatio="xMidYMid slice"
      aria-hidden={title ? undefined : true}
      role={title ? "img" : undefined}
    >
      {title ? <title>{title}</title> : null}
      <rect width={w} height={h} fill={palette.bg} />
      {body}
      {showCaption ? <Caption meta={meta} w={w} h={h} palette={palette} /> : null}
    </svg>
  );
}

/* HTML overlay caption used on top of raster assets. */
function CaptionOverlay({ meta, palette }: { meta: CompositionMeta; palette: Palette }) {
  return (
    <div
      style={{
        position: "absolute",
        left: "5%",
        bottom: "5%",
        color: palette.caption,
        textShadow:
          palette === DARK
            ? "0 1px 2px rgba(0,0,0,0.55)"
            : "0 1px 1px rgba(255,255,255,0.4)",
        pointerEvents: "none",
      }}
    >
      <div
        style={{
          fontSize: 11,
          letterSpacing: "0.22em",
          fontWeight: 600,
          textTransform: "uppercase",
          opacity: 0.9,
        }}
      >
        {meta.label}
      </div>
      <div
        style={{
          marginTop: 4,
          fontSize: 12,
          opacity: 0.7,
          fontStyle: "italic",
        }}
      >
        {meta.caption}
      </div>
    </div>
  );
}

/* Per-tone palette. */
const LIGHT = {
  bg: "#EAE7E2",        // warm paper
  ink: "#0A0A0A",        // ink
  inkSoft: "#2A2A2A",
  inkFaint: "#8A8A8A",
  caption: "#0A0A0A",
};
const DARK = {
  bg: "#0A0A0A",
  ink: "#F4F2EE",
  inkSoft: "#C0BDB8",
  inkFaint: "#5A5854",
  caption: "#F4F2EE",
};
type Palette = typeof LIGHT;

/* Caption: "01.  FRAGMENTATION  / Signal breaks through structure." */
function Caption({
  meta,
  w,
  h,
  palette,
}: {
  meta: CompositionMeta;
  w: number;
  h: number;
  palette: Palette;
}) {
  const padX = w * 0.05;
  const padY = h * 0.06;
  return (
    <g>
      <text
        x={padX}
        y={h - padY - 22}
        fill={palette.caption}
        fontFamily="ui-sans-serif, system-ui, sans-serif"
        fontSize="14"
        fontWeight="500"
        letterSpacing="3"
        opacity="0.85"
      >
        {meta.label.toUpperCase()}
      </text>
      <text
        x={padX}
        y={h - padY}
        fill={palette.caption}
        fontFamily="ui-sans-serif, system-ui, sans-serif"
        fontSize="13"
        opacity="0.55"
      >
        {meta.caption}
      </text>
    </g>
  );
}

/* ─── Dispatch ─────────────────────────────────────────────────────────── */

type Renderer = (seed: number, w: number, h: number, p: Palette) => React.ReactNode;

const RENDERERS: Record<CompositionTheme, Renderer> = {
  fragmentation,
  absence,
  structure,
  interruption,
};

/* ═══════════════════════════════════════════════════════════════════════ */
/*  THEMES                                                                  */
/* ═══════════════════════════════════════════════════════════════════════ */

/* ─── fragmentation ────────────────────────────────────────────────────── */

function fragmentation(seed: number, w: number, h: number, p: Palette): React.ReactNode {
  const rand = mulberry32(seed);
  const elems: React.ReactNode[] = [];

  /* Implied vertical "presence" — a column where bands break or weaken. */
  const presenceCx = w * (0.38 + rand() * 0.24);
  const presenceWidth = w * (0.18 + rand() * 0.16);
  const presenceTop = h * (0.18 + rand() * 0.08);
  const presenceBot = h * (0.78 + rand() * 0.08);

  /* Dense horizontal bands fill the entire field. Most are nearly opaque ink;
     a minority are thinner / lighter. Some bands break across the presence. */
  let y = -2;
  let key = 0;
  while (y < h) {
    const bandH = 1 + Math.pow(rand(), 1.4) * 7;       // skew thinner
    const bandY = y + bandH / 2;
    const inPresence = bandY > presenceTop && bandY < presenceBot;
    const breakBand = inPresence && rand() > 0.45;
    const opacity = 0.78 + rand() * 0.22;

    if (breakBand) {
      // Two segments left and right of the presence
      const gapW = presenceWidth * (0.4 + rand() * 0.6);
      const gapStart = presenceCx - gapW / 2;
      const gapEnd = presenceCx + gapW / 2;
      if (gapStart > 0)
        elems.push(<rect key={key++} x={0} y={y} width={gapStart} height={bandH} fill={p.ink} opacity={opacity} />);
      if (gapEnd < w)
        elems.push(<rect key={key++} x={gapEnd} y={y} width={w - gapEnd} height={bandH} fill={p.ink} opacity={opacity} />);
      // Faint trace inside the presence column
      if (rand() > 0.6) {
        elems.push(
          <rect
            key={key++}
            x={gapStart}
            y={y + bandH * 0.35}
            width={gapEnd - gapStart}
            height={bandH * 0.3}
            fill={p.inkFaint}
            opacity="0.35"
          />
        );
      }
    } else {
      elems.push(<rect key={key++} x={0} y={y} width={w} height={bandH} fill={p.ink} opacity={opacity} />);
    }

    /* Occasional thin gap (paper showing through). */
    const gap = rand() < 0.12 ? 1 + rand() * 3 : 0;
    y += bandH + gap;
  }

  /* A few hairline interrupts running full width — registration marks. */
  const hairlineCount = 3 + Math.floor(rand() * 4);
  for (let i = 0; i < hairlineCount; i++) {
    const hy = h * (0.05 + rand() * 0.9);
    elems.push(
      <rect key={`hl${i}`} x={0} y={hy} width={w} height="0.4" fill={p.bg} opacity={0.65 + rand() * 0.3} />
    );
  }

  return <>{elems}</>;
}

/* ─── absence ──────────────────────────────────────────────────────────── */

function absence(seed: number, w: number, h: number, p: Palette): React.ReactNode {
  const rand = mulberry32(seed);
  const elems: React.ReactNode[] = [];

  /* Subtle horizon line. */
  const horizonY = h * (0.62 + rand() * 0.06);
  elems.push(
    <line
      key="horizon"
      x1={w * 0.08}
      y1={horizonY}
      x2={w * 0.92}
      y2={horizonY}
      stroke={p.inkFaint}
      strokeWidth="0.6"
      opacity="0.3"
    />
  );

  /* Dominant top mark — circle, dome, or arch. */
  const variant = seed % 4;
  const cx = w * (0.42 + rand() * 0.16);
  const topY = h * (0.30 + rand() * 0.06);
  const baseR = Math.min(w, h) * (0.13 + rand() * 0.05);

  if (variant === 0) {
    // Filled circle
    elems.push(<circle key="top" cx={cx} cy={topY} r={baseR} fill={p.ink} />);
  } else if (variant === 1) {
    // Half-dome (semicircle, flat side down)
    elems.push(
      <path
        key="top"
        d={`M ${cx - baseR} ${topY + baseR * 0.05} A ${baseR} ${baseR} 0 0 1 ${cx + baseR} ${topY + baseR * 0.05} Z`}
        fill={p.ink}
      />
    );
  } else if (variant === 2) {
    // Arch — rectangle with rounded top
    const archH = baseR * 1.7;
    const archW = baseR * 1.1;
    elems.push(
      <path
        key="top"
        d={`
          M ${cx - archW} ${topY + archH}
          L ${cx - archW} ${topY}
          A ${archW} ${archW} 0 0 1 ${cx + archW} ${topY}
          L ${cx + archW} ${topY + archH}
          Z
        `}
        fill={p.ink}
      />
    );
  } else {
    // Two-stacked: small dot above a larger circle
    elems.push(
      <circle key="top1" cx={cx} cy={topY - baseR * 1.4} r={baseR * 0.18} fill={p.ink} />,
      <circle key="top2" cx={cx} cy={topY} r={baseR} fill={p.ink} />
    );
  }

  /* Lower void — small dark rectangle near horizon, slightly off the dominant axis. */
  const voidJitter = (rand() - 0.5) * w * 0.16;
  const voidW = w * (0.025 + rand() * 0.025);
  const voidH = voidW * (1.6 + rand() * 1.4);
  const voidX = cx + voidJitter - voidW / 2;
  const voidY = horizonY - voidH * 0.05;
  elems.push(<rect key="void" x={voidX} y={voidY} width={voidW} height={voidH} fill={p.ink} />);

  /* Optional far smaller second mark, silent companion. */
  if ((seed >>> 5) % 3 === 0) {
    const otherX = cx + (rand() > 0.5 ? 1 : -1) * w * (0.18 + rand() * 0.12);
    elems.push(<circle key="other" cx={otherX} cy={horizonY - 4} r={1.6 + rand() * 1.4} fill={p.ink} opacity="0.65" />);
  }

  /* Hairline registration marks at corners — institutional feel. */
  const tickLen = 14;
  const margin = 28;
  const tone = p.inkFaint;
  const cornerTicks = [
    [margin, margin, margin + tickLen, margin],
    [margin, margin, margin, margin + tickLen],
    [w - margin, margin, w - margin - tickLen, margin],
    [w - margin, margin, w - margin, margin + tickLen],
    [margin, h - margin, margin + tickLen, h - margin],
    [margin, h - margin, margin, h - margin - tickLen],
    [w - margin, h - margin, w - margin - tickLen, h - margin],
    [w - margin, h - margin, w - margin, h - margin - tickLen],
  ];
  cornerTicks.forEach(([x1, y1, x2, y2], i) => {
    elems.push(
      <line key={`tk${i}`} x1={x1} y1={y1} x2={x2} y2={y2} stroke={tone} strokeWidth="0.6" opacity="0.45" />
    );
  });

  return <>{elems}</>;
}

/* ─── structure ────────────────────────────────────────────────────────── */

function structure(seed: number, w: number, h: number, p: Palette): React.ReactNode {
  const rand = mulberry32(seed);
  const elems: React.ReactNode[] = [];

  const cols = 4 + (seed % 4); // 4..7
  const rows = cols + (((seed >>> 3) % 2) === 0 ? 0 : 1);
  const padX = w * (0.08 + rand() * 0.04);
  const padY = h * (0.08 + rand() * 0.04);
  const gridW = w - 2 * padX;
  const gridH = h - 2 * padY;
  const cellW = gridW / cols;
  const cellH = gridH / rows;

  /* Outer frame. */
  elems.push(
    <rect
      key="frame"
      x={padX}
      y={padY}
      width={gridW}
      height={gridH}
      stroke={p.ink}
      strokeWidth="2"
      fill="none"
    />
  );
  /* Inner grid lines. */
  for (let i = 1; i < cols; i++) {
    elems.push(
      <line
        key={`v${i}`}
        x1={padX + i * cellW}
        y1={padY}
        x2={padX + i * cellW}
        y2={padY + gridH}
        stroke={p.ink}
        strokeWidth="0.6"
        opacity="0.7"
      />
    );
  }
  for (let i = 1; i < rows; i++) {
    elems.push(
      <line
        key={`h${i}`}
        x1={padX}
        y1={padY + i * cellH}
        x2={padX + gridW}
        y2={padY + i * cellH}
        stroke={p.ink}
        strokeWidth="0.6"
        opacity="0.7"
      />
    );
  }

  /* Filled cells — sparse rhythm. ~18-32% of cells. */
  const fillRatio = 0.18 + rand() * 0.14;
  const filled = new Set<string>();
  const target = Math.floor(rows * cols * fillRatio);
  let attempts = 0;
  while (filled.size < target && attempts < target * 4) {
    attempts++;
    const r = Math.floor(rand() * rows);
    const c = Math.floor(rand() * cols);
    filled.add(`${r}-${c}`);
  }
  Array.from(filled).forEach((key) => {
    const [r, c] = key.split("-").map(Number);
    elems.push(
      <rect
        key={`f${key}`}
        x={padX + c * cellW + 0.5}
        y={padY + r * cellH + 0.5}
        width={cellW - 1}
        height={cellH - 1}
        fill={p.ink}
      />
    );
  });

  /* Occasional spanning bars — 2-cell wide rectangle drawn over a row or column. */
  if ((seed >>> 7) % 2 === 0) {
    const r = Math.floor(rand() * rows);
    const cStart = Math.floor(rand() * (cols - 2));
    const span = 2 + Math.floor(rand() * 2);
    elems.push(
      <rect
        key="span"
        x={padX + cStart * cellW + 0.5}
        y={padY + r * cellH + 0.5}
        width={cellW * span - 1}
        height={cellH - 1}
        fill={p.ink}
      />
    );
  }

  return <>{elems}</>;
}

/* ─── interruption ─────────────────────────────────────────────────────── */

function interruption(seed: number, w: number, h: number, p: Palette): React.ReactNode {
  const rand = mulberry32(seed);
  const elems: React.ReactNode[] = [];

  /* Subtle radial vignette to add atmosphere. */
  const vignetteId = `vg-${seed}`;
  elems.push(
    <defs key="defs">
      <radialGradient id={vignetteId} cx="50%" cy="50%" r="65%">
        <stop offset="0%" stopColor={p.inkFaint} stopOpacity="0.18" />
        <stop offset="100%" stopColor={p.bg} stopOpacity="0" />
      </radialGradient>
      <linearGradient id={`zip-${seed}`} x1="0" y1="0" x2="1" y2="0">
        <stop offset="0%" stopColor={p.ink} stopOpacity="0" />
        <stop offset="35%" stopColor={p.ink} stopOpacity="0.4" />
        <stop offset="50%" stopColor={p.ink} stopOpacity="1" />
        <stop offset="65%" stopColor={p.ink} stopOpacity="0.4" />
        <stop offset="100%" stopColor={p.ink} stopOpacity="0" />
      </linearGradient>
    </defs>
  );
  elems.push(<rect key="vignette" width={w} height={h} fill={`url(#${vignetteId})`} />);

  /* The vertical zip — main bar plus a feathered halo via the linear gradient. */
  const zipX = w * (0.40 + rand() * 0.20);
  const zipBaseW = 4 + rand() * 4;
  const zipTop = h * (0.20 + rand() * 0.12);
  const zipBot = h * (0.92 + rand() * 0.04);

  /* Soft halo — wide gradient bar. */
  const haloW = zipBaseW * 14;
  elems.push(
    <rect
      key="halo"
      x={zipX - haloW / 2}
      y={zipTop}
      width={haloW}
      height={zipBot - zipTop}
      fill={`url(#zip-${seed})`}
      opacity="0.45"
    />
  );

  /* Main zip bar. */
  elems.push(
    <rect
      key="zip"
      x={zipX - zipBaseW / 2}
      y={zipTop}
      width={zipBaseW}
      height={zipBot - zipTop}
      fill={p.ink}
    />
  );

  /* Bright nucleus at the top of the zip — sometimes a circular flare. */
  const flareSize = zipBaseW * (1.2 + rand() * 1.5);
  elems.push(
    <circle key="flare" cx={zipX} cy={zipTop} r={flareSize} fill={p.ink} opacity="0.85" />,
    <circle key="flare2" cx={zipX} cy={zipTop} r={flareSize * 2.2} fill={p.ink} opacity="0.18" />
  );

  /* Optional scattered far-field debris — tiny bright dots. */
  const debris = 6 + Math.floor(rand() * 8);
  for (let i = 0; i < debris; i++) {
    const dx = w * (0.05 + rand() * 0.9);
    const dy = h * (0.05 + rand() * 0.9);
    /* Skip if too close to the zip — preserve its silence. */
    if (Math.abs(dx - zipX) < zipBaseW * 4) continue;
    elems.push(
      <circle key={`db${i}`} cx={dx} cy={dy} r={0.6 + rand() * 1} fill={p.ink} opacity={0.18 + rand() * 0.25} />
    );
  }

  /* Faint floor line at very bottom — establishes a stage. */
  const floorY = h * 0.93;
  elems.push(
    <line
      key="floor"
      x1={w * 0.1}
      y1={floorY}
      x2={w * 0.9}
      y2={floorY}
      stroke={p.ink}
      strokeWidth="0.6"
      opacity="0.4"
    />
  );

  return <>{elems}</>;
}
